/**
 * Cloudflare Turnstile Server-Side Verification
 *
 * Verifies the token generated by the frontend Turnstile widget.
 * If credentials are missing, it defaults to TRUE (success) to allow development.
 */
export async function verifyTurnstileToken(token: string, ip?: string): Promise<boolean> {
  const secretKey = process.env.TURNSTILE_SECRET_KEY;

  // 1. Dev/Mock Mode: If no key is set, allow the request
  if (!secretKey) {
    if (process.env.NODE_ENV === 'production') {
      console.error('🚨 SECURITY WARNING: Turnstile enabled but TURNSTILE_SECRET_KEY is missing!');
    } else {
      console.log('ℹ️ Turntile Verification: Skipped (Missing TURNSTILE_SECRET_KEY)');
    }
    return true;
  }

  // 2. Verify with Cloudflare
  try {
    const formData = new FormData();
    formData.append('secret', secretKey);
    formData.append('response', token);
    if (ip) formData.append('remoteip', ip);

    const result = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
      method: 'POST',
      body: formData,
    });

    const outcome = (await result.json()) as {
      success: boolean;
      'error-codes'?: string[];
    };

    if (!outcome.success) {
      console.warn('❌ Turnstile Verification Failed:', outcome['error-codes']);
      return false;
    }

    return true;
  } catch (error) {
    console.error('Turnstile verification error:', error);
    // In strict mode, you might want to return false here.
    // For now, fail open to prevent blocking legitimate users during outages.
    return true;
  }
}
